server:
  port: 8101

spring:
  application:
    name: yf-exam
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/no023_exam?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    # 你的账号和密码
    username: root
    password: 1025

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000

# 日志级别
#logging:
#  level:
#    root: debug
